import { hashSemanticValue } from '@shapeshift-labs/frontier-lang-kernel';
import { parseHtmlSemanticRecords } from './parser-evidence.js';
export { createHtmlRuntimeBoundaryProof, createHtmlRuntimeProof } from './runtime-proof.js';
export { safeMergeHtmlSource } from './semantic-merge.js';

const VoidTags = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr']);
const RuntimeBoundaryTags = new Set(['script', 'style', 'template', 'slot']);

export function toHtmlAst(document, options = {}) {
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-html.';
  const body = [];
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'entity' || node.kind === 'type') body.push(sectionNode(node, node.fields ?? []));
    if (node.kind === 'action') body.push(elementNode('button', { type: 'button', 'data-frontier-action': node.name }, [textNode(node.name)], sourceRef(node)));
    if (node.kind === 'capability') body.push(elementNode('div', { 'data-frontier-capability': node.capability, 'data-frontier-category': node.category }, [textNode(node.name)], sourceRef(node)));
    if (node.kind === 'lattice') body.push(elementNode('div', { 'data-frontier-lattice': node.name, 'data-frontier-carrier': String(node.carrier ?? '') }, [textNode(node.name)], sourceRef(node)));
  }
  return { kind: 'html.document', banner, children: [elementNode('main', { 'data-frontier-document': document.name ?? document.id }, body)] };
}

export function renderHtmlAst(ast) {
  return renderHtmlAstWithSourceMap(ast).code;
}

export function renderHtmlAstWithSourceMap(ast, options = {}) {
  const lines = [`<!-- ${escapeText(ast.banner)} -->`];
  const mappings = [];
  ast.children.forEach((node, index) => renderHtmlNode(lines, mappings, node, 0, index, options));
  const code = `${lines.join('\n').trimEnd()}\n`;
  return { code, sourceMap: sourceMapEnvelope(ast, mappings, options) };
}

export function emitHtml(document, options = {}) {
  return renderHtmlAst(toHtmlAst(document, options));
}

export function emitHtmlWithSourceMap(document, options = {}) {
  const ast = toHtmlAst(document, options);
  const result = renderHtmlAstWithSourceMap(ast, { sourceMapId: options.sourceMapId ?? `sourcemap_${idFragment(document.id)}_html`, ...options });
  return { ...result, ast };
}

export function parseHtmlSemanticTree(sourceText, options = {}) {
  const parsed = parseHtmlSemanticRecords(sourceText, options);
  const records = parsed.records;
  const proofGaps = parsed.proofGaps;
  return {
    kind: 'frontier.lang.htmlSemanticTree',
    version: 1,
    sourcePath: options.sourcePath,
    sourceHash: parsed.sourceHash,
    records,
    treeHash: parsed.treeHash,
    summary: {
      elements: records.filter((record) => record.kind === 'element').length,
      textNodes: records.filter((record) => record.kind === 'text').length,
      comments: records.filter((record) => record.kind === 'comment').length,
      proofGaps: proofGaps.length,
      parseErrors: parsed.parser.parseErrors.length
    },
    proofGaps,
    parser: parsed.parser
  };
}

export function createHtmlSemanticMergeEvidence(sourceText, options = {}) {
  const tree = parseHtmlSemanticTree(sourceText, options);
  return {
    kind: 'frontier.lang.htmlSemanticMergeEvidence',
    version: 1,
    status: tree.proofGaps.length ? 'needs-review' : 'ready',
    sourcePath: options.sourcePath,
    sourceHash: tree.sourceHash,
    treeHash: tree.treeHash,
    records: tree.records,
    proofGaps: tree.proofGaps,
    autoMergeClaim: false,
    semanticEquivalenceClaim: false,
    browserRuntimeEquivalenceClaim: false
  };
}

function sectionNode(node, fields) {
  return elementNode('section', { 'data-frontier-kind': node.kind, 'data-frontier-name': node.name }, [
    elementNode('h2', {}, [textNode(node.name)]),
    elementNode('ul', {}, fields.map((field) => elementNode('li', { 'data-frontier-field': field.name, 'data-frontier-type': typeName(field.type) }, [textNode(field.name)], sourceRef(node, { regionIds: [field.id] }))))
  ], sourceRef(node, { regionIds: fields.map((field) => field.id) }));
}

function elementNode(tagName, attributes = {}, children = [], sourceRefValue) {
  return { kind: 'element', tagName, attributes: cleanObject(attributes), children, sourceRef: sourceRefValue };
}

function textNode(value) { return { kind: 'text', value: String(value ?? '') }; }
function sourceRef(node, extra = {}) { return { semanticNodeId: node.id, semanticNodeKind: node.kind, semanticNodeName: node.name, ...extra }; }

function renderHtmlNode(lines, mappings, node, depth, ordinal, options) {
  const indent = '  '.repeat(depth);
  if (node.kind === 'text') {
    lines.push(`${indent}${escapeText(node.value)}`);
    return;
  }
  const startLine = lines.length + 1;
  const attrs = Object.entries(node.attributes ?? {}).map(([key, value]) => ` ${key}="${escapeAttribute(value)}"`).join('');
  lines.push(`${indent}<${node.tagName}${attrs}>`);
  for (const child of node.children ?? []) renderHtmlNode(lines, mappings, child, depth + 1, ordinal, options);
  lines.push(`${indent}</${node.tagName}>`);
  if (node.sourceRef?.semanticNodeId) mappings.push(sourceMapMapping(node, mappings.length, startLine, lines.length, options));
}

function pushElementRecord(token, offset, lineStarts, sourceHash, stack, records) {
  const parsed = parseStartTag(token);
  if (!parsed) return;
  const parent = stack.at(-1);
  const ordinal = nextOrdinal(parent, parsed.tagName);
  const path = [...parent.path, `${parsed.tagName}[${ordinal}]`];
  const proofGaps = htmlProofGaps(parsed);
  const record = compactRecord({
    kind: 'element',
    tagName: parsed.tagName,
    path,
    ordinal,
    identityKey: parsed.attributes.id ?? parsed.attributes['data-frontier-key'] ?? path.join('/'),
    attributes: parsed.attributes,
    classList: parsed.attributes.class?.split(/\s+/).filter(Boolean),
    sourceSpan: sourceSpan(offset, offset + token.length, lineStarts),
    sourceHash,
    attributeHash: hashSemanticValue({ kind: 'frontier.lang.html.attributes.v1', attributes: parsed.attributes }),
    proofGaps: proofGaps.length ? proofGaps : undefined
  });
  records.push(record);
  if (!parsed.selfClosing && !VoidTags.has(parsed.tagName)) stack.push({ tagName: parsed.tagName, childCounts: new Map(), path });
}

function pushTextRecord(sourceText, start, end, lineStarts, sourceHash, stack, records) {
  const text = sourceText.slice(start, end);
  if (!text.trim()) return;
  const parent = stack.at(-1);
  const ordinal = nextOrdinal(parent, '#text');
  records.push({
    kind: 'text',
    path: [...parent.path, `#text[${ordinal}]`],
    textHash: hashSemanticValue({ kind: 'frontier.lang.html.text.v1', text }),
    sourceSpan: sourceSpan(start, end, lineStarts),
    sourceHash
  });
}

function pushCommentRecord(token, offset, lineStarts, sourceHash, stack, records) {
  const parent = stack.at(-1);
  const ordinal = nextOrdinal(parent, '#comment');
  records.push({
    kind: 'comment',
    path: [...parent.path, `#comment[${ordinal}]`],
    commentHash: hashSemanticValue({ kind: 'frontier.lang.html.comment.v1', text: token }),
    sourceSpan: sourceSpan(offset, offset + token.length, lineStarts),
    sourceHash
  });
}

function closeElement(token, stack) {
  const tagName = token.replace(/^<\//, '').replace(/>$/, '').trim().toLowerCase();
  for (let index = stack.length - 1; index > 0; index -= 1) {
    if (stack[index].tagName === tagName) {
      stack.length = index;
      return;
    }
  }
}

function parseStartTag(token) {
  const match = /^<([A-Za-z][\w:-]*)([\s\S]*?)\/?>$/.exec(token);
  if (!match) return undefined;
  return {
    tagName: match[1].toLowerCase(),
    attributes: parseAttributes(match[2] ?? ''),
    selfClosing: /\/>$/.test(token)
  };
}

function parseAttributes(text) {
  const result = {};
  const pattern = /([:@A-Za-z_][\w:.-]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/g;
  for (const match of text.matchAll(pattern)) result[match[1]] = match[2] ?? match[3] ?? match[4] ?? true;
  return result;
}

function htmlProofGaps(parsed) {
  const gaps = [];
  if (RuntimeBoundaryTags.has(parsed.tagName)) gaps.push(proofGap(`${parsed.tagName}-runtime-boundary`, `HTML <${parsed.tagName}> runtime/template semantics require host evidence.`));
  if (parsed.tagName.includes('-')) gaps.push(proofGap('custom-element-runtime-boundary', 'Custom element upgrade and lifecycle semantics require browser/runtime evidence.'));
  if (Object.keys(parsed.attributes).some((key) => key.startsWith('@') || key.startsWith(':') || key.startsWith('v-') || key.startsWith('x-'))) gaps.push(proofGap('framework-directive-boundary', 'Framework directive semantics require framework-specific evidence.'));
  return gaps;
}

function proofGap(code, summary) { return { code, status: 'not-claimed', summary, failClosed: true, semanticEquivalenceClaim: false }; }
function nextOrdinal(parent, key) { const next = (parent.childCounts.get(key) ?? 0) + 1; parent.childCounts.set(key, next); return next; }
function hashableHtmlRecord(record) { return { kind: record.kind, tagName: record.tagName, path: record.path, identityKey: record.identityKey, attributes: record.attributes, textHash: record.textHash, commentHash: record.commentHash, proofGaps: record.proofGaps?.map((gap) => gap.code) }; }

function sourceMapMapping(node, ordinal, startLine, endLine, options) {
  return compactRecord({
    id: `map_${idFragment(node.sourceRef.semanticNodeId)}_${ordinal}`,
    semanticNodeId: node.sourceRef.semanticNodeId,
    sourceSpan: options.sourceSpansBySemanticNodeId?.[node.sourceRef.semanticNodeId],
    generatedSpan: { path: options.targetPath, targetPath: options.targetPath, target: { language: 'html' }, generatedName: node.tagName, startLine, startColumn: 1, endLine, endColumn: 1 },
    target: { language: 'html' },
    generatedName: node.tagName,
    precision: 'element-block',
    metadata: { semanticNodeKind: node.sourceRef.semanticNodeKind, semanticNodeName: node.sourceRef.semanticNodeName, regionIds: node.sourceRef.regionIds }
  });
}

function sourceMapEnvelope(ast, mappings, options) {
  return compactRecord({ kind: 'frontier.lang.sourceMap', version: 1, id: options.sourceMapId ?? `sourcemap_${idFragment(ast.kind)}_html`, sourcePath: options.sourcePath, sourceHash: options.sourceHash, target: { language: 'html' }, targetPath: options.targetPath, semanticIndexId: options.semanticIndexId, mappings, evidence: options.evidence ?? [], metadata: { precision: 'element-block', generatedSpanStrategy: 'html-renderer-element-block' } });
}

function sourceSpan(start, end, lineStarts) {
  const from = positionAt(start, lineStarts);
  const to = positionAt(end, lineStarts);
  return { startOffset: start, endOffset: end, startLine: from.line, startColumn: from.column, endLine: to.line, endColumn: to.column };
}

function positionAt(offset, lineStarts) {
  let line = 0;
  while (line + 1 < lineStarts.length && lineStarts[line + 1] <= offset) line += 1;
  return { line: line + 1, column: offset - lineStarts[line] + 1 };
}

function computeLineStarts(text) { const starts = [0]; for (let index = 0; index < text.length; index += 1) if (text[index] === '\n') starts.push(index + 1); return starts; }
function escapeText(value) { return String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function escapeAttribute(value) { return escapeText(value).replace(/"/g, '&quot;'); }
function typeName(type) { return typeof type === 'string' ? type : type?.name ?? type?.kind ?? 'unknown'; }
function cleanObject(object) { return Object.fromEntries(Object.entries(object).filter(([, value]) => value !== undefined)); }
function compactRecord(record) { return Object.fromEntries(Object.entries(record).filter(([, value]) => value !== undefined)); }
function idFragment(value) { return String(value ?? 'unknown').replace(/[^A-Za-z0-9_$]/g, '_').replace(/^_+/, '') || 'unknown'; }
